/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StockInRouteImport } from './routes/stock-in'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InseminationRouteImport } from './routes/insemination'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoUserIdRouteImport } from './routes/catalogo.$userId'

const StockInRoute = StockInRouteImport.update({
  id: '/stock-in',
  path: '/stock-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InseminationRoute = InseminationRouteImport.update({
  id: '/insemination',
  path: '/insemination',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoUserIdRoute = CatalogoUserIdRouteImport.update({
  id: '/catalogo/$userId',
  path: '/catalogo/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/history': typeof HistoryRoute
  '/insemination': typeof InseminationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/stock-in': typeof StockInRoute
  '/catalogo/$userId': typeof CatalogoUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/history': typeof HistoryRoute
  '/insemination': typeof InseminationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/stock-in': typeof StockInRoute
  '/catalogo/$userId': typeof CatalogoUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/history': typeof HistoryRoute
  '/insemination': typeof InseminationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/stock-in': typeof StockInRoute
  '/catalogo/$userId': typeof CatalogoUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/history'
    | '/insemination'
    | '/login'
    | '/onboarding'
    | '/products'
    | '/register'
    | '/settings'
    | '/shopping'
    | '/stock-in'
    | '/catalogo/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/history'
    | '/insemination'
    | '/login'
    | '/onboarding'
    | '/products'
    | '/register'
    | '/settings'
    | '/shopping'
    | '/stock-in'
    | '/catalogo/$userId'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/history'
    | '/insemination'
    | '/login'
    | '/onboarding'
    | '/products'
    | '/register'
    | '/settings'
    | '/shopping'
    | '/stock-in'
    | '/catalogo/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  HistoryRoute: typeof HistoryRoute
  InseminationRoute: typeof InseminationRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProductsRoute: typeof ProductsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRoute
  StockInRoute: typeof StockInRoute
  CatalogoUserIdRoute: typeof CatalogoUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock-in': {
      id: '/stock-in'
      path: '/stock-in'
      fullPath: '/stock-in'
      preLoaderRoute: typeof StockInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insemination': {
      id: '/insemination'
      path: '/insemination'
      fullPath: '/insemination'
      preLoaderRoute: typeof InseminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$userId': {
      id: '/catalogo/$userId'
      path: '/catalogo/$userId'
      fullPath: '/catalogo/$userId'
      preLoaderRoute: typeof CatalogoUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  HistoryRoute: HistoryRoute,
  InseminationRoute: InseminationRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProductsRoute: ProductsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRoute,
  StockInRoute: StockInRoute,
  CatalogoUserIdRoute: CatalogoUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
